spin_manifest_version = 2

[application]
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "0.1.0"

[[trigger.http]]
route = "{{http-path}}"
component = "{{project-name | kebab_case}}"

[component.{{project-name | kebab_case}}]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "dist/", destination = "/" }]
exclude_files = ["**/node_modules"]

[component.{{project-name | kebab_case}}.build]
command = "pnpm build"
watch = ["src/**/*.tsx", "src/**/*.*css"]