manifest_version = "1"
id = "qwik-frontend"
description = "Front-end application using Qwik and Spin"
tags = ["qwik", "frontend", "front-end", "fe", "web"]

[add_component]
skip_files = ["spin.toml"]
skip_parameters = ["http-base"]

[add_component.snippets]
component = "component.txt"

[parameters]
project-description = { type = "string", prompt = "Project description", default = "" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }